//
// Created by Øystein Bringsli.
//

#ifndef LINE_FOLLOWING_ROBOT_PLATFORMIO_MOTORSIGNAL_HPP
#define LINE_FOLLOWING_ROBOT_PLATFORMIO_MOTORSIGNAL_HPP


class MotorSignal {

};


#endif //LINE_FOLLOWING_ROBOT_PLATFORMIO_MOTORSIGNAL_HPP
